name: Publish

on:
  push:
    branches:
      - "28-hash-check"
  workflow_call:
    inputs:
      VERSION:
        description: 'Version name'
        required: true
        type: string
    secrets:
      GH_AUTH:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20', '1.23']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Update go.mod go version
        run: |
          sed -i 's/^go [0-9.]\+/go ${{ matrix.go-version }}/' go.mod

      - name: Build binaries for Linux, macOS, and Windows
        run: |
          mkdir -p dist

          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/${{ matrix.go-version }}/echo-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o dist/${{ matrix.go-version }}/echo-darwin-amd64 .
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o dist/${{ matrix.go-version }}/echo-windows-amd64.exe .
          
      - name: List output files
        run: ls -lh dist

      - name: Upload
        uses: IdanKoblik/Changelog@prod
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH }}
        with:
          version: ${{ inputs.VERSION || 'test-go-version' }}
          assets: '["./dist/${{ matrix.go-version }}/*"]'