name: Lint

on:
  workflow_call:
    inputs:
      GO:
        required: true
        type: string
        
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
